### ISSUE TITLE
It doesn't run on python3

### ISSUE THREAD

**Issue by hatimhtm** [a6avind/spoofcheck#1]
![image](https://user-images.githubusercontent.com/106043141/191802965-a0c8d933-aa2f-40c4-a58a-41e9518ebbf3.png)

I keep getting this issue over and over.

**Comment by kbayodetroya** [comment]
I have a similar problem; however, it tells me the following: ython3 spoofcheck.py domain.tld
Traceback (most recent call last):
  File "/scripts/spoofcheck/spoofcheck.py", line 5, in <module>
    import emailprotectionslib.dmarc as dmarc_lib
  File "/usr/local/lib/python3.10/dist-packages/emailprotectionslib/dmarc.py", line 3, in <module>
    import Resolver
ModuleNotFoundError: No module named 'Resolver'

**Comment by a6avind** [comment]
Thank you for using the tools.
As sanity check, wanted to confirm whether you guys have installed all the dependencies?

**Comment by a6avind** [comment]
I am closing the issue since I haven't gotten a response yet. However, please feel free to reopen if the problem continues.
