### ISSUE TITLE
Module bot found 

### ISSUE THREAD

**Issue by PYC0RD** [a6avind/spoofcheck#3]
I don't know why but his showing this error 
ModuleNotFoundError: No module named 'Resolver'

**Comment by a6avind** [comment]
Hi @Nebu134, Thank you for trying out the tool. Can you please share the entire error trace to get the complete picture? I just tried it on my side, and it works as expected.
Make sure that you have installed the required libraries.

**Comment by PYC0RD** [comment]
Thank you for responding to my issues 
 And yes I installed the requirements.txt
And when I run the tool i get this error 

./spoofcheck.py google.com

Traceback (most recent call last):
  File "/home/kali/g/spoofcheck/./spoofcheck.py", line 7, in <module>
    import emailprotectionslib.dmarc as dmarclib
  File "/usr/local/lib/python3.11/dist-packages/emailprotectionslib/dmarc.py", line 3, in <module>
    import Resolver
ModuleNotFoundError: No module named 'Resolver'

 I installed Resolver but it still doesn't work

**Comment by a6avind** [comment]
Oh, that's strange. Can you create a virtual environment and try to run it from there?

**Comment by Nebu134** [comment]
Yes it works thank you for helping me

**Comment by Nebu134** [comment]
Yes it works thank you for helping me

**Comment by PYC0RD** [comment]
Yes it works thank you for helping me

**Comment by PYC0RD** [comment]
Yes it works thank you for helping me

**Comment by a6avind** [comment]
Python libraries can be a pain to manage sometimes. It's good to know that it worked for you.
